### ISSUE TITLE
consider marking this repo deprecated and providing link to line of forks

### ISSUE THREAD

**Issue by Poikilos** [chadaustin/audiere#1]
There is a good deal of confusion regarding the status of Audiere. **1.9.4 still is the package in many linux distros, and doesn't have support for sound systems newer than oss** and requires alsa-oss for oss emulation though that is not stated as a dependency (just fails and secretly says `missing /dev/dsp` in console), whereas, in contrast current forks have pulse and alsa as well as compatibility with modern versions of Windows. There are many people improving it on here, but they forked slightly before you did (I know because they are only missing certain [only a few] changes from your svn repo on sourceforge--I added any missing ones back in). If you make changes, please make them to a fork that is updated instead of here. I have forked from someone who included **pulse** and several other sound systems and fixed some stuff to work on later Windows compilers. I edited it some more, keeping all that good stuff, but also to once again build with gnu build tools. With your team's work in svn, and the GitHub forks, and my work, the [changelog since the last release version is colossal](https://github.com/expertmm/Audiere/releases). My repo is <https://github.com/expertmm/Audiere>
The AUR people are still working on 1.9.4 from time to time, so I implemented their diffs as well and let them know. I also bumped the version to follow semantic versioning.

As opposed to deleting repo, ideal solution would be something like: <https://stackoverflow.com/questions/22457959/current-best-practice-for-retiring-a-project-on-github-and-npmjs-org/22597985#22597985>

**Comment by chadaustin** [comment]
Hi @expertmm.  I haven't touched Audiere in years (as you know) and did not realize others had forked and were maintaining it!  That's very cool and I'm glad to hear it.

This GitHub repo is merely my personal backup of my SourceForge repos.  I'll add a README.md redirecting people to your fork!

Is there work to get your version into Linux distributions?

**Comment by Poikilos** [comment]
The github forks include the last (2011) changes done in the sourceforge svn repo, plus many additions. I started from there and got it to compile in linux again (both with libtool and scons, though scons would mostly be used for a cygwin build I figured). It is tested and working on linux using a program I wrote, and the console example can play a sound using alsa or pulse. I still need to fully migrate the wx example to wx3 but it compiles now on wx3. I am in communication with AUR about using my release. I will eventually contact others once I get the wx example working--that would make for a better show of quality.

**Comment by Poikilos** [comment]
Could you put a note and a link on the sourceforge project (and [website](http://audiere.sourceforge.net/)) linking to my or other GitHub fork? <https://github.com/expertmm/Audiere>

**Comment by Poikilos** [comment]
@chadaustin  I changed my username to poikilos. Please update links.

**Comment by chadaustin** [comment]
Links updated in 25238a032beb014b22d34b226d9b8d9dd8248ef4
